/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsSitemapDotxmlRouteImport } from './routes/news-sitemap[.]xml'
import { Route as FactCheckingPolicyRouteImport } from './routes/fact-checking-policy'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CorrectionsPolicyRouteImport } from './routes/corrections-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as CategoryCategoryRouteImport } from './routes/category.$category'
import { Route as AuthorNameRouteImport } from './routes/author.$name'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminNewRouteImport } from './routes/_authenticated/admin.new'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as AuthenticatedAdminVideosIndexRouteImport } from './routes/_authenticated/admin.videos.index'
import { Route as AuthenticatedAdminAdsIndexRouteImport } from './routes/_authenticated/admin.ads.index'
import { Route as AuthenticatedAdminVideosNewRouteImport } from './routes/_authenticated/admin.videos.new'
import { Route as AuthenticatedAdminEditIdRouteImport } from './routes/_authenticated/admin.edit.$id'
import { Route as AuthenticatedAdminAdsNewRouteImport } from './routes/_authenticated/admin.ads.new'
import { Route as AuthenticatedAdminVideosEditIdRouteImport } from './routes/_authenticated/admin.videos.edit.$id'
import { Route as AuthenticatedAdminAdsEditIdRouteImport } from './routes/_authenticated/admin.ads.edit.$id'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSitemapDotxmlRoute = NewsSitemapDotxmlRouteImport.update({
  id: '/news-sitemap.xml',
  path: '/news-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FactCheckingPolicyRoute = FactCheckingPolicyRouteImport.update({
  id: '/fact-checking-policy',
  path: '/fact-checking-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectionsPolicyRoute = CorrectionsPolicyRouteImport.update({
  id: '/corrections-policy',
  path: '/corrections-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorNameRoute = AuthorNameRouteImport.update({
  id: '/author/$name',
  path: '/author/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminNewRoute = AuthenticatedAdminNewRouteImport.update({
  id: '/admin/new',
  path: '/admin/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/admin/import',
    path: '/admin/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVideosIndexRoute =
  AuthenticatedAdminVideosIndexRouteImport.update({
    id: '/admin/videos/',
    path: '/admin/videos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAdsIndexRoute =
  AuthenticatedAdminAdsIndexRouteImport.update({
    id: '/admin/ads/',
    path: '/admin/ads/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVideosNewRoute =
  AuthenticatedAdminVideosNewRouteImport.update({
    id: '/admin/videos/new',
    path: '/admin/videos/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEditIdRoute =
  AuthenticatedAdminEditIdRouteImport.update({
    id: '/admin/edit/$id',
    path: '/admin/edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAdsNewRoute =
  AuthenticatedAdminAdsNewRouteImport.update({
    id: '/admin/ads/new',
    path: '/admin/ads/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVideosEditIdRoute =
  AuthenticatedAdminVideosEditIdRouteImport.update({
    id: '/admin/videos/edit/$id',
    path: '/admin/videos/edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAdsEditIdRoute =
  AuthenticatedAdminAdsEditIdRouteImport.update({
    id: '/admin/ads/edit/$id',
    path: '/admin/ads/edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/corrections-policy': typeof CorrectionsPolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/fact-checking-policy': typeof FactCheckingPolicyRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/videos': typeof VideosRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/author/$name': typeof AuthorNameRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/news/$slug': typeof NewsSlugRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/ads/new': typeof AuthenticatedAdminAdsNewRoute
  '/admin/edit/$id': typeof AuthenticatedAdminEditIdRoute
  '/admin/videos/new': typeof AuthenticatedAdminVideosNewRoute
  '/admin/ads/': typeof AuthenticatedAdminAdsIndexRoute
  '/admin/videos/': typeof AuthenticatedAdminVideosIndexRoute
  '/admin/ads/edit/$id': typeof AuthenticatedAdminAdsEditIdRoute
  '/admin/videos/edit/$id': typeof AuthenticatedAdminVideosEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/corrections-policy': typeof CorrectionsPolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/fact-checking-policy': typeof FactCheckingPolicyRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/videos': typeof VideosRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/author/$name': typeof AuthorNameRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/news/$slug': typeof NewsSlugRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/ads/new': typeof AuthenticatedAdminAdsNewRoute
  '/admin/edit/$id': typeof AuthenticatedAdminEditIdRoute
  '/admin/videos/new': typeof AuthenticatedAdminVideosNewRoute
  '/admin/ads': typeof AuthenticatedAdminAdsIndexRoute
  '/admin/videos': typeof AuthenticatedAdminVideosIndexRoute
  '/admin/ads/edit/$id': typeof AuthenticatedAdminAdsEditIdRoute
  '/admin/videos/edit/$id': typeof AuthenticatedAdminVideosEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/corrections-policy': typeof CorrectionsPolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/fact-checking-policy': typeof FactCheckingPolicyRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/videos': typeof VideosRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/author/$name': typeof AuthorNameRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/news/$slug': typeof NewsSlugRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/new': typeof AuthenticatedAdminNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/ads/new': typeof AuthenticatedAdminAdsNewRoute
  '/_authenticated/admin/edit/$id': typeof AuthenticatedAdminEditIdRoute
  '/_authenticated/admin/videos/new': typeof AuthenticatedAdminVideosNewRoute
  '/_authenticated/admin/ads/': typeof AuthenticatedAdminAdsIndexRoute
  '/_authenticated/admin/videos/': typeof AuthenticatedAdminVideosIndexRoute
  '/_authenticated/admin/ads/edit/$id': typeof AuthenticatedAdminAdsEditIdRoute
  '/_authenticated/admin/videos/edit/$id': typeof AuthenticatedAdminVideosEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/corrections-policy'
    | '/disclaimer'
    | '/editorial-policy'
    | '/fact-checking-policy'
    | '/news-sitemap.xml'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/videos'
    | '/api/ai-chat'
    | '/author/$name'
    | '/category/$category'
    | '/news/$slug'
    | '/admin/import'
    | '/admin/new'
    | '/admin/'
    | '/admin/ads/new'
    | '/admin/edit/$id'
    | '/admin/videos/new'
    | '/admin/ads/'
    | '/admin/videos/'
    | '/admin/ads/edit/$id'
    | '/admin/videos/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/corrections-policy'
    | '/disclaimer'
    | '/editorial-policy'
    | '/fact-checking-policy'
    | '/news-sitemap.xml'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/videos'
    | '/api/ai-chat'
    | '/author/$name'
    | '/category/$category'
    | '/news/$slug'
    | '/admin/import'
    | '/admin/new'
    | '/admin'
    | '/admin/ads/new'
    | '/admin/edit/$id'
    | '/admin/videos/new'
    | '/admin/ads'
    | '/admin/videos'
    | '/admin/ads/edit/$id'
    | '/admin/videos/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/corrections-policy'
    | '/disclaimer'
    | '/editorial-policy'
    | '/fact-checking-policy'
    | '/news-sitemap.xml'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/videos'
    | '/api/ai-chat'
    | '/author/$name'
    | '/category/$category'
    | '/news/$slug'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/new'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/ads/new'
    | '/_authenticated/admin/edit/$id'
    | '/_authenticated/admin/videos/new'
    | '/_authenticated/admin/ads/'
    | '/_authenticated/admin/videos/'
    | '/_authenticated/admin/ads/edit/$id'
    | '/_authenticated/admin/videos/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CorrectionsPolicyRoute: typeof CorrectionsPolicyRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  FactCheckingPolicyRoute: typeof FactCheckingPolicyRoute
  NewsSitemapDotxmlRoute: typeof NewsSitemapDotxmlRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VideosRoute: typeof VideosRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  AuthorNameRoute: typeof AuthorNameRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  NewsSlugRoute: typeof NewsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-sitemap.xml': {
      id: '/news-sitemap.xml'
      path: '/news-sitemap.xml'
      fullPath: '/news-sitemap.xml'
      preLoaderRoute: typeof NewsSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fact-checking-policy': {
      id: '/fact-checking-policy'
      path: '/fact-checking-policy'
      fullPath: '/fact-checking-policy'
      preLoaderRoute: typeof FactCheckingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrections-policy': {
      id: '/corrections-policy'
      path: '/corrections-policy'
      fullPath: '/corrections-policy'
      preLoaderRoute: typeof CorrectionsPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/$name': {
      id: '/author/$name'
      path: '/author/$name'
      fullPath: '/author/$name'
      preLoaderRoute: typeof AuthorNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/new': {
      id: '/_authenticated/admin/new'
      path: '/admin/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AuthenticatedAdminNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/videos/': {
      id: '/_authenticated/admin/videos/'
      path: '/admin/videos'
      fullPath: '/admin/videos/'
      preLoaderRoute: typeof AuthenticatedAdminVideosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ads/': {
      id: '/_authenticated/admin/ads/'
      path: '/admin/ads'
      fullPath: '/admin/ads/'
      preLoaderRoute: typeof AuthenticatedAdminAdsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/videos/new': {
      id: '/_authenticated/admin/videos/new'
      path: '/admin/videos/new'
      fullPath: '/admin/videos/new'
      preLoaderRoute: typeof AuthenticatedAdminVideosNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/edit/$id': {
      id: '/_authenticated/admin/edit/$id'
      path: '/admin/edit/$id'
      fullPath: '/admin/edit/$id'
      preLoaderRoute: typeof AuthenticatedAdminEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ads/new': {
      id: '/_authenticated/admin/ads/new'
      path: '/admin/ads/new'
      fullPath: '/admin/ads/new'
      preLoaderRoute: typeof AuthenticatedAdminAdsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/videos/edit/$id': {
      id: '/_authenticated/admin/videos/edit/$id'
      path: '/admin/videos/edit/$id'
      fullPath: '/admin/videos/edit/$id'
      preLoaderRoute: typeof AuthenticatedAdminVideosEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ads/edit/$id': {
      id: '/_authenticated/admin/ads/edit/$id'
      path: '/admin/ads/edit/$id'
      fullPath: '/admin/ads/edit/$id'
      preLoaderRoute: typeof AuthenticatedAdminAdsEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminNewRoute: typeof AuthenticatedAdminNewRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminAdsNewRoute: typeof AuthenticatedAdminAdsNewRoute
  AuthenticatedAdminEditIdRoute: typeof AuthenticatedAdminEditIdRoute
  AuthenticatedAdminVideosNewRoute: typeof AuthenticatedAdminVideosNewRoute
  AuthenticatedAdminAdsIndexRoute: typeof AuthenticatedAdminAdsIndexRoute
  AuthenticatedAdminVideosIndexRoute: typeof AuthenticatedAdminVideosIndexRoute
  AuthenticatedAdminAdsEditIdRoute: typeof AuthenticatedAdminAdsEditIdRoute
  AuthenticatedAdminVideosEditIdRoute: typeof AuthenticatedAdminVideosEditIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminNewRoute: AuthenticatedAdminNewRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminAdsNewRoute: AuthenticatedAdminAdsNewRoute,
  AuthenticatedAdminEditIdRoute: AuthenticatedAdminEditIdRoute,
  AuthenticatedAdminVideosNewRoute: AuthenticatedAdminVideosNewRoute,
  AuthenticatedAdminAdsIndexRoute: AuthenticatedAdminAdsIndexRoute,
  AuthenticatedAdminVideosIndexRoute: AuthenticatedAdminVideosIndexRoute,
  AuthenticatedAdminAdsEditIdRoute: AuthenticatedAdminAdsEditIdRoute,
  AuthenticatedAdminVideosEditIdRoute: AuthenticatedAdminVideosEditIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CorrectionsPolicyRoute: CorrectionsPolicyRoute,
  DisclaimerRoute: DisclaimerRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  FactCheckingPolicyRoute: FactCheckingPolicyRoute,
  NewsSitemapDotxmlRoute: NewsSitemapDotxmlRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VideosRoute: VideosRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  AuthorNameRoute: AuthorNameRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
  NewsSlugRoute: NewsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
